general {
	grab_focus = true
}

ui {
	window_size = 500 350
}

finders {
	default_finder = desktop
	desktop_icons = true
	match_prefix = =
	unicode_prefix = .
	font_prefix = '

	desktop_launch_prefix = 
}

cache {
	enabled = true
} 
