general.import = [
  "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"


[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16
